# Generated by Django 5.0.8 on 2024-08-30 13:09
# add UNIQUE to column 'name'

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0002_course_name_intake_end_date_intake_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                default="unnamed-course", max_length=50, unique=True
            ),
        ),
    ]
